os:
  - linux
language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
        artifacts: true
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
        artifacts: true
      env: COMPILER=g++-5

before_install:
  - . scripts/travis-$TRAVIS_OS_NAME.sh

script:
  - ./bootstrap.sh -a
  - ./configure
  - make
  - make test
